### ISSUE TITLE
Command `pack build` fails using the example

### ISSUE THREAD

**Issue by cmoulliard** [buildpack/pack#14] opened 2018-08-23 07:48 UTC
When we issue this command `./pack build myorg/myapp -p acceptance/fixtures/node_app --publish         `

then the following error is reported 

```
Error: failed to get image for packs/v3:run
```
even if we try to install manually using `docker pull` the image(s)

Full log

```
./pack build myorg/myapp -p acceptance/fixtures/node_app --publish                                  
*** DETECTING:
2018/08/23 07:43:34 Group: Sample Node.js Buildpack: pass
*** ANALYZING: Reading information from previous image for possible re-use
*** BUILDING:
Unable to find image 'packs/v3:build' locally
Trying to pull repository docker.io/packs/v3 ... 
build: Pulling from docker.io/packs/v3
c64513b74145: Already exists 
01b8b12bad90: Already exists 
c5d85cf7a05f: Already exists 
b6b268720157: Already exists 
e12192999ff1: Already exists 
9ec0afc3dd8c: Already exists 
8a8b744b79d4: Already exists 
c8c61c40292b: Already exists 
bfbfbd08c7bd: Already exists 
a1ecf4c48a82: Already exists 
9b4930b9f540: Already exists 
f0359eb7d8f7: Already exists 
3265a1e603ff: Pull complete 
8084fd95401b: Pull complete 
94bcec7355fb: Pull complete 
8264c669f1cf: Pull complete 
Digest: sha256:0358de438433568b3678bef43170795de8b9cfa174ecfc8131e625b96a48cd7c
Status: Downloaded newer image for docker.io/packs/v3:build
express@4.16.3 /launch/app/node_modules/express
accepts@1.3.5 /launch/app/node_modules/express/node_modules/accepts
mime-types@2.1.19 /launch/app/node_modules/express/node_modules/mime-types
mime-db@1.35.0 /launch/app/node_modules/express/node_modules/mime-db
negotiator@0.6.1 /launch/app/node_modules/express/node_modules/negotiator
array-flatten@1.1.1 /launch/app/node_modules/express/node_modules/array-flatten
body-parser@1.18.2 /launch/app/node_modules/express/node_modules/body-parser
bytes@3.0.0 /launch/app/node_modules/express/node_modules/bytes
content-type@1.0.4 /launch/app/node_modules/express/node_modules/content-type
debug@2.6.9 /launch/app/node_modules/express/node_modules/debug
ms@2.0.0 /launch/app/node_modules/express/node_modules/ms
depd@1.1.2 /launch/app/node_modules/express/node_modules/depd
http-errors@1.6.3 /launch/app/node_modules/express/node_modules/http-errors
inherits@2.0.3 /launch/app/node_modules/express/node_modules/inherits
setprototypeof@1.1.0 /launch/app/node_modules/express/node_modules/setprototypeof
statuses@1.4.0 /launch/app/node_modules/express/node_modules/statuses
iconv-lite@0.4.19 /launch/app/node_modules/express/node_modules/iconv-lite
on-finished@2.3.0 /launch/app/node_modules/express/node_modules/on-finished
ee-first@1.1.1 /launch/app/node_modules/express/node_modules/ee-first
qs@6.5.1 /launch/app/node_modules/express/node_modules/qs
raw-body@2.3.2 /launch/app/node_modules/express/node_modules/raw-body
http-errors@1.6.2 /launch/app/node_modules/express/node_modules/raw-body/node_modules/http-errors
depd@1.1.1 /launch/app/node_modules/express/node_modules/raw-body/node_modules/depd
setprototypeof@1.0.3 /launch/app/node_modules/express/node_modules/raw-body/node_modules/setprototypeof
unpipe@1.0.0 /launch/app/node_modules/express/node_modules/unpipe
type-is@1.6.16 /launch/app/node_modules/express/node_modules/type-is
media-typer@0.3.0 /launch/app/node_modules/express/node_modules/media-typer
content-disposition@0.5.2 /launch/app/node_modules/express/node_modules/content-disposition
cookie@0.3.1 /launch/app/node_modules/express/node_modules/cookie
cookie-signature@1.0.6 /launch/app/node_modules/express/node_modules/cookie-signature
encodeurl@1.0.2 /launch/app/node_modules/express/node_modules/encodeurl
escape-html@1.0.3 /launch/app/node_modules/express/node_modules/escape-html
etag@1.8.1 /launch/app/node_modules/express/node_modules/etag
finalhandler@1.1.1 /launch/app/node_modules/express/node_modules/finalhandler
parseurl@1.3.2 /launch/app/node_modules/express/node_modules/parseurl
fresh@0.5.2 /launch/app/node_modules/express/node_modules/fresh
merge-descriptors@1.0.1 /launch/app/node_modules/express/node_modules/merge-descriptors
methods@1.1.2 /launch/app/node_modules/express/node_modules/methods
path-to-regexp@0.1.7 /launch/app/node_modules/express/node_modules/path-to-regexp
proxy-addr@2.0.4 /launch/app/node_modules/express/node_modules/proxy-addr
forwarded@0.1.2 /launch/app/node_modules/express/node_modules/forwarded
ipaddr.js@1.8.0 /launch/app/node_modules/express/node_modules/ipaddr.js
range-parser@1.2.0 /launch/app/node_modules/express/node_modules/range-parser
safe-buffer@5.1.1 /launch/app/node_modules/express/node_modules/safe-buffer
send@0.16.2 /launch/app/node_modules/express/node_modules/send
destroy@1.0.4 /launch/app/node_modules/express/node_modules/destroy
mime@1.4.1 /launch/app/node_modules/express/node_modules/mime
serve-static@1.13.2 /launch/app/node_modules/express/node_modules/serve-static
utils-merge@1.0.1 /launch/app/node_modules/express/node_modules/utils-merge
vary@1.1.2 /launch/app/node_modules/express/node_modules/vary
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN app@1.0.0 No description
npm WARN app@1.0.0 No repository field.

up to date in 0.347s
*** EXPORTING:
Error: failed to get image for packs/v3:run
Usage:
  pack build [IMAGE NAME] [flags]

Flags:
      --detect-image string   detect image (default "packs/v3:detect")
  -h, --help                  help for build
  -p, --path string           path to app dir (default "/Users/dabou/Code/go-workspace/src/github.com/buildpack/pack")
  -r, --publish               publish to registry

docker pull packs/v3:run                                          
Trying to pull repository docker.io/packs/v3 ... 
run: Pulling from docker.io/packs/v3
c64513b74145: Already exists 
01b8b12bad90: Already exists 
c5d85cf7a05f: Already exists 
b6b268720157: Already exists 
e12192999ff1: Already exists 
9ec0afc3dd8c: Already exists 
8a8b744b79d4: Already exists 
c8c61c40292b: Already exists 
bfbfbd08c7bd: Already exists 
3c1241c68295: Pull complete 
Digest: sha256:793a13d1c313063dcc77713ec63338fa790588fc4b1c0a3dfb4b751bda18343d
Status: Downloaded newer image for docker.io/packs/v3:run

 ./pack build myorg/myapp -p acceptance/fixtures/node_app --publish
*** DETECTING:
2018/08/23 07:44:28 Group: Sample Node.js Buildpack: pass
*** ANALYZING: Reading information from previous image for possible re-use
*** BUILDING:
express@4.16.3 /launch/app/node_modules/express
accepts@1.3.5 /launch/app/node_modules/express/node_modules/accepts
mime-types@2.1.19 /launch/app/node_modules/express/node_modules/mime-types
mime-db@1.35.0 /launch/app/node_modules/express/node_modules/mime-db
negotiator@0.6.1 /launch/app/node_modules/express/node_modules/negotiator
array-flatten@1.1.1 /launch/app/node_modules/express/node_modules/array-flatten
body-parser@1.18.2 /launch/app/node_modules/express/node_modules/body-parser
bytes@3.0.0 /launch/app/node_modules/express/node_modules/bytes
content-type@1.0.4 /launch/app/node_modules/express/node_modules/content-type
debug@2.6.9 /launch/app/node_modules/express/node_modules/debug
ms@2.0.0 /launch/app/node_modules/express/node_modules/ms
depd@1.1.2 /launch/app/node_modules/express/node_modules/depd
http-errors@1.6.3 /launch/app/node_modules/express/node_modules/http-errors
inherits@2.0.3 /launch/app/node_modules/express/node_modules/inherits
setprototypeof@1.1.0 /launch/app/node_modules/express/node_modules/setprototypeof
statuses@1.4.0 /launch/app/node_modules/express/node_modules/statuses
iconv-lite@0.4.19 /launch/app/node_modules/express/node_modules/iconv-lite
on-finished@2.3.0 /launch/app/node_modules/express/node_modules/on-finished
ee-first@1.1.1 /launch/app/node_modules/express/node_modules/ee-first
qs@6.5.1 /launch/app/node_modules/express/node_modules/qs
raw-body@2.3.2 /launch/app/node_modules/express/node_modules/raw-body
http-errors@1.6.2 /launch/app/node_modules/express/node_modules/raw-body/node_modules/http-errors
depd@1.1.1 /launch/app/node_modules/express/node_modules/raw-body/node_modules/depd
setprototypeof@1.0.3 /launch/app/node_modules/express/node_modules/raw-body/node_modules/setprototypeof
unpipe@1.0.0 /launch/app/node_modules/express/node_modules/unpipe
type-is@1.6.16 /launch/app/node_modules/express/node_modules/type-is
media-typer@0.3.0 /launch/app/node_modules/express/node_modules/media-typer
content-disposition@0.5.2 /launch/app/node_modules/express/node_modules/content-disposition
cookie@0.3.1 /launch/app/node_modules/express/node_modules/cookie
cookie-signature@1.0.6 /launch/app/node_modules/express/node_modules/cookie-signature
encodeurl@1.0.2 /launch/app/node_modules/express/node_modules/encodeurl
escape-html@1.0.3 /launch/app/node_modules/express/node_modules/escape-html
etag@1.8.1 /launch/app/node_modules/express/node_modules/etag
finalhandler@1.1.1 /launch/app/node_modules/express/node_modules/finalhandler
parseurl@1.3.2 /launch/app/node_modules/express/node_modules/parseurl
fresh@0.5.2 /launch/app/node_modules/express/node_modules/fresh
merge-descriptors@1.0.1 /launch/app/node_modules/express/node_modules/merge-descriptors
methods@1.1.2 /launch/app/node_modules/express/node_modules/methods
path-to-regexp@0.1.7 /launch/app/node_modules/express/node_modules/path-to-regexp
proxy-addr@2.0.4 /launch/app/node_modules/express/node_modules/proxy-addr
forwarded@0.1.2 /launch/app/node_modules/express/node_modules/forwarded
ipaddr.js@1.8.0 /launch/app/node_modules/express/node_modules/ipaddr.js
range-parser@1.2.0 /launch/app/node_modules/express/node_modules/range-parser
safe-buffer@5.1.1 /launch/app/node_modules/express/node_modules/safe-buffer
send@0.16.2 /launch/app/node_modules/express/node_modules/send
destroy@1.0.4 /launch/app/node_modules/express/node_modules/destroy
mime@1.4.1 /launch/app/node_modules/express/node_modules/mime
serve-static@1.13.2 /launch/app/node_modules/express/node_modules/serve-static
utils-merge@1.0.1 /launch/app/node_modules/express/node_modules/utils-merge
vary@1.1.2 /launch/app/node_modules/express/node_modules/vary
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN app@1.0.0 No description
npm WARN app@1.0.0 No repository field.

up to date in 0.296s
*** EXPORTING:
Error: failed to get image for packs/v3:run
Usage:
  pack build [IMAGE NAME] [flags]

Flags:
      --detect-image string   detect image (default "packs/v3:detect")
  -h, --help                  help for build
  -p, --path string           path to app dir (default "/Users/dabou/Code/go-workspace/src/github.com/buildpack/pack")
  -r, --publish               publish to registry
```

Is it a bug or a step not described within the doc ?

**Comment by sclevine** [comment] 2018-08-23 16:01
Are you publishing to DockerHub?

**Comment by cmoulliard** [comment] 2018-08-24 05:53
> DockerHub

No but using a local docker registry running on k8s/openshift

**Comment by dgodd** [comment] 2018-10-18 16:09
@cmoulliard Are you still experiencing this issue?

**Comment by cmoulliard** [comment] 2018-10-22 09:06
I did a new test using version `v0.0.4` of the pack tool and I'm getting this error now 

```
 ./pack build myorg/myapp -p acceptance/fixtures/node_app          
2018/10/22 11:04:17 Pulling builder image 'packs/samples' (use --no-pull flag to skip this step)
2018/10/22 11:04:19 Selected run image 'packs/run' from stack 'io.buildpacks.stacks.bionic'
2018/10/22 11:04:19 Pulling run image 'packs/run' (use --no-pull flag to skip this step)
Error: invalid run image "packs/run": missing required label "io.buildpacks.stack.id"
Usage:
  pack build <image-name> [flags]

Flags:
      --builder string     builder (default "packs/samples")
  -h, --help               help for build
      --no-pull            don't pull images before use
  -p, --path string        path to app dir (default "/Users/dabou/Code/go-workspace/src/github.com/buildpack/pack")
      --publish            publish to registry
      --run-image string   run image
```

**Comment by ekcasey** [comment] 2018-10-22 20:55
@cmoulliard I just tried and couldn't reproduce this with pack `v0.0.4`. A couple quick questions...

On which OS are you running?
What version of the docker daemon are you running?
If you run ` docker inspect packs/run --format '{{.Config.Labels}}'` do you see a `io.buildpacks.stack.id` key in the output?

**Comment by ekcasey** [comment] 2018-12-12 20:07
@cmoulliard Given that we are several versions ahead of `v0.0.4` now I am going to close this. Please don't hesitate to open a new issue if you are experiencing problems with `v0.0.7` or `v0.0.8`.

**Closed by ekcasey** 2018-12-12 20:07 UTC
