### ISSUE TITLE
Exclude specified directories

### ISSUE THREAD

**Issue by Zanadar** [buildpack/pack#403] opened 2019-12-04 00:53 UTC
Can we somehow support exclusions for subfolders of apps that we don't want to be considered for a build, eg. `./vendor`?

Could be a flag, `.packignore`, both?

**Comment by Zanadar** [comment] 2019-12-04 00:54
CC @fuel-lightning

**Comment by Zanadar** [comment] 2019-12-04 00:55
> Is there a way to exclude a directory from being used in the building when using pack build ? I’m specifically trying to not include the vendor folder, since my local dev env uses that, but the builder doesn’t want it as it resolves it’s own dependencies? I’m not seeing anything specific from pack build --help

**Comment by jromero** [comment] 2019-12-04 01:52
Closing this as a duplicate of #210

**TL;DR**: We are currently planning to incorporate this sort of functionality in a feature that is currently in the RFC process (https://github.com/buildpack/rfcs/pull/25).

**Closed by jromero** 2019-12-04 01:52 UTC
