### ISSUE TITLE
Suggestion: use "Squash and merge" instead of a merge for pull request

### ISSUE THREAD

**Issue by neerfri** [buildpack/pack#201] opened 2019-05-29 20:27 UTC
Hi CNB members!

Great appreciation for the project. Thank you for contributing your time to improve everyones workflow.

I'd like to suggest an admin of this repository will [disable the normal "merge button" in GitHub](https://help.github.com/en/articles/configuring-commit-squashing-for-pull-requests) so that pull requests that are merged in this repository are merged as a single change and are shown on the git history of the master in the right point in time.
This makes it much easier for your users to understand the changes that happened between versions.

For example see the [current changes from `v0.2.0` to `master`](https://github.com/buildpack/pack/compare/v0.2.0...master):
![image](https://user-images.githubusercontent.com/21379/58579304-95b7b900-81ff-11e9-9f3b-b46b04d18a2f.png)

The counter argument has always been that defaulting to squash merge "deletes" the journey that the developers working on the changes have gone. In the case of Github that is not really correct since the original PR and it's associated branch are always available with all their commits, comments and checks. Frankly it's more common that the commits are not a good representation of the parts that compose the pull request, with lots of "fix typo" and revert commits.

As a user of many OSS projects I can say that those that switched to squash merges are much easier for me to navigate and contribute to.

**Comment by sclevine** [comment] 2019-05-29 22:29
Thanks for the suggestion @neerfri! I'm glad that you appreciate the project.

Up to this point, our philosophy has been "don't re-write other people's work."

To me, avoiding rebasing/squashing on merge is less about preserving the user journey, and more about preserving the sanctity of original author's contributions. Consider that contributors may PGP sign their commits and/or expect that the authorship of each commit be preserved as-is. It's difficult to know what a PR submitter is comfortable with, and it isn't practical to ask each submitter. 

Additionally, the CNCF requires that each commit into the project contain a DCO sign-off from whomever authored the code. I assume that these are supposed to be preserved after the merge (but I'm not certain).

**Comment by neerfri** [comment] 2019-05-30 03:33
@sclevine Thanks for your response.

As you can see below, kubernetes, that has similar requirements and similar mindset is using a form of squash-merge for their master:
![image](https://user-images.githubusercontent.com/21379/58605870-45b41300-824e-11e9-84ce-4ef0ad1366db.png)


Just to make sure I am understood. We are not expecting any developer to rebase or squash their commits. We are talking about an automatic button in GitHub that does something very similar to `git merge --squash` (not the same as squash via `git rebase -i`)
See https://maori.geek.nz/githubs-squash-and-merge-doesn-t-squash-and-doesn-t-merge-5044be7cd124 for expansion on this.

The PGP signatures will remain in the original PR and should be validated **before** the PR is approved for merging.

The authorship of the commit is preserved as-is, in the context of the PR.
With squash-merge, fat-finger-authorship (which sometimes happens...) will not leak to `master`

**Comment by ekcasey** [comment] 2019-05-30 13:19
I am supportive of this idea. It's nice when the git history is informative.

**Comment by jromero** [comment] 2019-06-10 21:07
I'd like to support this as well with the addition of stating that reverting a feature (PR) is much easier when it's only a single commit instead of a collection of commits that need to be "rolled-back".

**Comment by ekcasey** [comment] 2019-06-11 22:24
@neerfri I changed the `pack` repo settings.

@sclevine Last chance to object, otherwise I will close this

**Comment by sclevine** [comment] 2019-06-11 22:40
I changed it back for now. I'd prefer input from the other project owners before we decide. I also think a project-wide policy makes more sense.

Personally, I still feel strongly about keeping the current policy. I don't believe that PGP signatures only exist to verify commits before they are merged, and I don't believe in re-writing other people's commit history. Git was designed to deal with non-linear history. Throwing history away because Github has poor UX for it seems unfortunate.

As Linus puts it:

>  You must never EVER destroy other peoples history. You must not rebase 
>   commits other people did. Basically, if it doesn't have your sign-off 
>  on it, it's off limits: you can't rebase it, because it's not yours.

https://www.mail-archive.com/dri-devel@lists.sourceforge.net/msg39091.html

**Comment by jasonkuhrt** [comment] 2019-06-22 18:49
I'm not sure I'm following the squash rebase rewrites history issue. It does not affect the the PR history, just allows for a clear and manageable master branch. Github keeps references to the PR in master commit messages (just a pr number like in comments will do). If one is curious the untouched paper trail is there, and available.

**Comment by ekcasey** [comment] 2019-11-08 23:02
This conversation has been quiet for awhile. Currently, we don't intend to make this change. Feel free to reopen if you want to continue the discussion :)

**Closed by ekcasey** 2019-11-08 23:02 UTC
